### ISSUE TITLE
10월 먼슬리 미팅 안건

### ISSUE THREAD

**Issue by koptimizer** [hhhminme/kpu_sandol_team#19]
### 운영
- 이용률 절감에 따른 홍보 전략 수립
- 레포 리드미에 프레임워크 아키텍쳐 피겨 추가
- 광고주 모집 전략 수립

### 데브
- 광고주님들을 위한 통계 기능 추가 검토
- 향후 모듈 의존성 문제 발생 가능성 검토

<br/>
<b>추가 안건은 스레드처럼 남겨주세요.</b>

**Comment by hhhminme** [comment]
확인했습니다. 관련하여 자세한 사항은 미팅때 이야기 해보겠습니다. 10월 먼슬리 미팅은 며칠로 생각하고 계신가요?

**Comment by koptimizer** [comment]
@hhhminme 
중간고사, 향후 교내 코로나 대응 지침 등을 보고 유동적으로 결정하게 될 것 같습니다만, 10월 초순으로 생각중입니다.

**Comment by koptimizer** [comment]
### 운영
- 이용률 절감에 따른 홍보 전략 수립 -> 광종, 민
  - 홍보물
  - 참여 형식의 이벤트성 시나리오 계획
- 레포 리드미에 프레임워크 아키텍쳐 피겨 추가 -> 지호, 민
  - 우선순위는 낮으나 필요한 부분
- 광고주 모집 전략 수립 -> 광종
  - 현재 있는 홍보물을 먼저 사용해야 함
  - 지속적으로 생각 필요
  
### 데브
- 광고주님들을 위한 통계 기능 추가 검토 -> 지호, 준하
  - 보류 <- Lambda 태생의 문제... 
  - Lambda <- RDB 연동 생각...
  - 백오피스를 웹으로..!?
- 향후 모듈 의존성 문제 발생 가능성 검토 -> 지호
  - 모듈 체크 및 기록

### Others
- 도서관 번호 수정 -> 광종
