### ISSUE TITLE
11월 먼슬리 미팅 안건

### ISSUE THREAD

**Issue by koptimizer** [hhhminme/kpu_sandol_team#21]
### 운영
- 미가 이슈 토의
- 산돌이 홍보 계획
- 광고주 모집 전략 수립

### 데브
- lambda_module 모듈화
- 레거시 코드 관리

**Comment by Cycrypto** [comment]
* lambda 함수 모듈화 회의전까지 완성 가능할거 같습니다.
     * 회의때 코드를 좀 확인해주셨으면 합니다. (가독성이나, 모듈화, 특히 main 함수부분)

**Comment by koptimizer** [comment]
확인하였습니다!

**Comment by koptimizer** [comment]
### 운영
- 미가 이슈 토의
  - 저와 민님이 미가에 한번 방문하기로...
  - 미가, 세미콘용 산돌이 포스터 제작 + 직접 붙여드리기
- 산돌이 홍보 계획
  - 포스터 
  - 포켓몬퀴즈 구현만
- 광고주 모집 전략 수립
  - 아트지 출력
  - 가격 고민

### 데브
- lambda_module 모듈화
  - 지호, 민, 광종 코드 리뷰 후, 금요일까지 피드백 달기
- 레거시 코드 관리
  - 준하, 광종
  
 ### do!
- 광종, 민: 외부식당 포스터제작 --> 다음주까지 미가 방문
- 지호, 민, 광종: 코드 리뷰
- 준하: 코드 머지
